
import xml.etree.ElementTree as ET
import json
import io

opml_data = {
    "United States": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="United States"><outline text="World News - Breaking News, Top Stories" xmlUrl="https://www.huffpost.com/section/world-news/feed" /><outline text="NYT > Top Stories" xmlUrl="https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml" /><outline text="FOX News" xmlUrl="http://feeds.foxnews.com/foxnews/latest" /><outline text="World" xmlUrl="http://feeds.washingtonpost.com/rss/world" /><outline text="WSJ.com: World News" xmlUrl="https://feeds.a.dj.com/rss/RSSWorldNews.xml" /><outline text="World & Nation" xmlUrl="https://www.latimes.com/world-nation/rss2.0.xml" /><outline text="CNN.com - RSS Channel - App International Edition" xmlUrl="http://rss.cnn.com/rss/edition.rss" /><outline text="Yahoo News - Latest News & Headlines" xmlUrl="https://news.yahoo.com/rss/mostviewed" /><outline text="US Top News and Analysis" xmlUrl="https://www.cnbc.com/id/100003114/device/rss/rss.html" /><outline text="Playbook" xmlUrl="https://rss.politico.com/playbook.xml" /></outline></body></opml>""",
    "United Kingdom": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="United Kingdom"><outline text="BBC News - Home" xmlUrl="http://feeds.bbci.co.uk/news/rss.xml" /><outline text="World news | The Guardian" xmlUrl="https://www.theguardian.com/world/rss" /><outline text="Home | Mail Online" xmlUrl="https://www.dailymail.co.uk/home/index.rss" /><outline text="The Independent" xmlUrl="http://www.independent.co.uk/news/uk/rss" /><outline text="Daily Express :: News Feed" xmlUrl="http://feeds.feedburner.com/daily-express-news-showbiz" /></outline></body></opml>""",
    "India": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="India"><outline text="BBC News - India" xmlUrl="http://feeds.bbci.co.uk/news/world/asia/india/rss.xml" /><outline text="India | The Guardian" xmlUrl="https://www.theguardian.com/world/india/rss" /><outline text="SEBI RSS Feed" xmlUrl="https://www.sebi.gov.in/sebirss.xml" /><outline text="Times of India" xmlUrl="https://timesofindia.indiatimes.com/rssfeedstopstories.cms" /><outline text="The Hindu - Home" xmlUrl="https://www.thehindu.com/feeder/default.rss" /><outline text="NDTV News - Topstories" xmlUrl="https://feeds.feedburner.com/ndtvnews-top-stories" /><outline text="India Today" xmlUrl="https://www.indiatoday.in/rss/home" /><outline text="The Indian Express" xmlUrl="http://indianexpress.com/print/front-page/feed/" /><outline text="News18" xmlUrl="https://www.news18.com/rss/world.xml" /><outline text="DNA India" xmlUrl="https://www.dnaindia.com/feeds/india.xml" /><outline text="Firstpost" xmlUrl="https://www.firstpost.com/rss/india.xml" /><outline text="Business Standard" xmlUrl="https://www.business-standard.com/rss/home_page_top_stories.rss" /><outline text="Outlook India" xmlUrl="https://www.outlookindia.com/rss/main/magazine" /><outline text="Free Press Journal" xmlUrl="https://www.freepressjournal.in/stories.rss" /><outline text="Deccan Chronicle" xmlUrl="https://www.deccanchronicle.com/rss_feed/" /><outline text="Moneycontrol" xmlUrl="http://www.moneycontrol.com/rss/latestnews.xml" /><outline text="Economic Times" xmlUrl="https://economictimes.indiatimes.com/rssfeedsdefault.cms" /></outline></body></opml>""",
    "Canada": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Canada"><outline text="CBC | Top Stories News" xmlUrl="https://www.cbc.ca/cmlink/rss-topstories" /><outline text="CTVNews.ca" xmlUrl="https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009" /><outline text="Financial Post" xmlUrl="https://business.financialpost.com/feed/" /><outline text="National Post" xmlUrl="https://nationalpost.com/feed/" /><outline text="Ottawa Citizen" xmlUrl="https://ottawacitizen.com/feed/" /><outline text="The Province" xmlUrl="https://theprovince.com/feed/" /><outline text="LaPresse.ca" xmlUrl="https://www.lapresse.ca/actualites/rss" /><outline text="Toronto Star" xmlUrl="https://www.thestar.com/content/thestar/feed.RSSManagerServlet.articles.topstories.rss" /><outline text="Toronto Sun" xmlUrl="https://torontosun.com/category/news/feed" /></outline></body></opml>""",
    "Australia": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Australia"><outline text="Daily Telegraph" xmlUrl="https://www.dailytelegraph.com.au/news/breaking-news/rss" /><outline text="Sydney Morning Herald" xmlUrl="https://www.smh.com.au/rss/feed.xml" /><outline text="Herald Sun" xmlUrl="https://www.heraldsun.com.au/news/breaking-news/rss" /><outline text="ABC News" xmlUrl="https://www.abc.net.au/news/feed/1948/rss.xml" /><outline text="The Age" xmlUrl="https://www.theage.com.au/rss/feed.xml" /><outline text="The Courier Mail" xmlUrl="https://www.couriermail.com.au/rss" /><outline text="PerthNow" xmlUrl="https://www.perthnow.com.au/news/feed" /><outline text="The Canberra Times" xmlUrl="https://www.canberratimes.com.au/rss.xml" /><outline text="Brisbane Times" xmlUrl="https://www.brisbanetimes.com.au/rss/feed.xml" /><outline text="Independent Australia" xmlUrl="http://feeds.feedburner.com/IndependentAustralia" /><outline text="Business News" xmlUrl="https://www.businessnews.com.au/rssfeed/latest.rss" /><outline text="The Mercury" xmlUrl="https://www.themercury.com.au/rss" /><outline text="Michael West" xmlUrl="https://www.michaelwest.com.au/feed/" /></outline></body></opml>""",
    "South Africa": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="South Africa"><outline text="SowetanLIVE" xmlUrl="https://www.sowetanlive.co.za/rss/?publication=sowetan-live" /><outline text="TechCentral" xmlUrl="https://techcentral.co.za/feed" /><outline text="News24" xmlUrl="http://feeds.news24.com/articles/news24/TopStories/rss" /><outline text="Eyewitness News" xmlUrl="https://ewn.co.za/RSS%20Feeds/Latest%20News" /><outline text="The Citizen" xmlUrl="https://citizen.co.za/feed/" /><outline text="Daily Maverick" xmlUrl="https://www.dailymaverick.co.za/dmrss/" /><outline text="Moneyweb" xmlUrl="https://www.moneyweb.co.za/feed/" /><outline text="IOL" xmlUrl="http://rss.iol.io/iol/news" /><outline text="TimesLIVE" xmlUrl="https://www.timeslive.co.za/rss/" /><outline text="The South African" xmlUrl="https://www.thesouthafrican.com/feed/" /><outline text="Axios" xmlUrl="https://api.axios.com/feed/" /></outline></body></opml>""",
    "Mexico": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Mexico"><outline text="The Guardian Mexico" xmlUrl="https://www.theguardian.com/world/mexico/rss" /><outline text="Excélsior" xmlUrl="https://www.excelsior.com.mx/rss.xml" /><outline text="Reforma" xmlUrl="https://www.reforma.com/rss/portada.xml" /><outline text="Vanguardia MX" xmlUrl="https://vanguardia.com.mx/rss.xml" /><outline text="El Financiero" xmlUrl="https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/?outputType=xml" /><outline text="ElNorte" xmlUrl="https://www.elnorte.com/rss/portada.xml" /><outline text="El Informador" xmlUrl="https://www.informador.mx/rss/ultimas-noticias.xml" /><outline text="24 Horas" xmlUrl="https://www.24-horas.mx/feed/" /><outline text="Mexico News Daily" xmlUrl="https://mexiconewsdaily.com/feed/" /><outline text="El Diario" xmlUrl="https://diario.mx/jrz/media/sitemaps/rss.xml" /></outline></body></opml>""",
    "Italy": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Italy"><outline text="ANSA.it" xmlUrl="https://www.ansa.it/sito/ansait_rss.xml" /><outline text="The Local" xmlUrl="https://feeds.thelocal.com/rss/it" /><outline text="DiariodelWeb.it" xmlUrl="https://www.diariodelweb.it/rss/home/" /><outline text="Fanpage" xmlUrl="https://www.fanpage.it/feed/" /><outline text="Libero Quotidiano" xmlUrl="https://www.liberoquotidiano.it/rss.xml" /><outline text="Il Mattino" xmlUrl="https://www.ilmattino.it/?sez=XML&args&p=search&args[box]=Home&limit=20&layout=rss" /><outline text="Adnkronos" xmlUrl="http://rss.adnkronos.com/RSS_PrimaPagina.xml" /><outline text="Milan News" xmlUrl="https://www.milannews.it/rss/" /><outline text="Internazionale" xmlUrl="https://www.internazionale.it/sitemaps/rss.xml" /><outline text="Panorama" xmlUrl="https://www.panorama.it/feeds/feed.rss" /><outline text="Repubblica.it" xmlUrl="https://www.repubblica.it/rss/homepage/rss2.0.xml" /><outline text="Il Post" xmlUrl="https://www.ilpost.it/feed/" /></outline></body></opml>""",
    "Spain": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Spain"><outline text="The Local" xmlUrl="https://feeds.thelocal.com/rss/es" /><outline text="EL PAÍS" xmlUrl="https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada" /><outline text="El Confidencial" xmlUrl="https://rss.elconfidencial.com/espana/" /><outline text="ElDiario.es" xmlUrl="https://www.eldiario.es/rss/" /><outline text="Expansion" xmlUrl="https://e00-expansion.uecdn.es/rss/portada.xml" /><outline text="El Periódico" xmlUrl="https://www.elperiodico.com/es/rss/rss_portada.xml" /><outline text="Huffington Post" xmlUrl="https://www.huffingtonpost.es/feeds/index.xml" /><outline text="Euro Weekly News" xmlUrl="https://www.euroweeklynews.com/feed/" /><outline text="Agencia EFE" xmlUrl="https://www.efe.com/efe/english/4/rss" /></outline></body></opml>""",
    "France": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="France"><outline text="france24.com" xmlUrl="https://www.france24.com/en/rss" /><outline text="Mediapart" xmlUrl="https://www.mediapart.fr/articles/feed" /><outline text="Le Monde" xmlUrl="https://www.lemonde.fr/rss/une.xml" /><outline text="L'Obs" xmlUrl="https://www.nouvelobs.com/a-la-une/rss.xml" /><outline text="Franceinfo" xmlUrl="https://www.francetvinfo.fr/titres.rss" /><outline text="Huffington Post" xmlUrl="https://www.huffingtonpost.fr/feeds/index.xml" /><outline text="La Dépêche" xmlUrl="https://www.ladepeche.fr/rss.xml" /><outline text="Ministry for Europe" xmlUrl="https://www.diplomatie.gouv.fr/spip.php?page=backend-fd&lang=en" /><outline text="Ouest-France" xmlUrl="https://www.ouest-france.fr/rss-en-continu.xml" /></outline></body></opml>""",
    "Germany": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Germany"><outline text="ZEIT ONLINE" xmlUrl="http://newsfeed.zeit.de/index" /><outline text="FOCUS Online" xmlUrl="https://rss.focus.de/fol/XML/rss_folnews.xml" /><outline text="FAZ.NET" xmlUrl="https://www.faz.net/rss/aktuell/" /><outline text="tagesschau.de" xmlUrl="http://www.tagesschau.de/xml/rss2" /><outline text="Deutsche Welle" xmlUrl="https://rss.dw.com/rdf/rss-en-all" /></outline></body></opml>""",
    "Japan": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Japan"><outline text="Japan Times" xmlUrl="https://www.japantimes.co.jp/feed/topstories/" /><outline text="Japan Today" xmlUrl="https://japantoday.com/feed" /><outline text="News On Japan" xmlUrl="http://www.newsonjapan.com/rss/top.xml" /><outline text="Kyodo News" xmlUrl="https://english.kyodonews.net/rss/all.xml" /><outline text="BRIDGE" xmlUrl="http://feeds.feedburner.com/SdJapan" /><outline text="NYT > Japan" xmlUrl="https://www.nytimes.com/svc/collections/v1/publish/http://www.nytimes.com/topic/destination/japan/rss.xml" /><outline text="Livedoor" xmlUrl="https://news.livedoor.com/topics/rss/top.xml" /><outline text="Asahi" xmlUrl="http://rss.asahi.com/rss/asahi/newsheadlines.rdf" /></outline></body></opml>""",
    "Brazil": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Brazil"><outline text="Folha de S.Paulo" xmlUrl="https://feeds.folha.uol.com.br/emcimadahora/rss091.xml" /><outline text="Portal EBC" xmlUrl="http://www.ebc.com.br/rss/feed.xml" /><outline text="R7" xmlUrl="https://noticias.r7.com/feed.xml" /><outline text="UOL" xmlUrl="http://rss.home.uol.com.br/index.xml" /><outline text="The Rio Times" xmlUrl="https://riotimesonline.com/feed/" /><outline text="Brasil Wire" xmlUrl="http://www.brasilwire.com/feed/" /><outline text="Jornal de Brasília" xmlUrl="https://jornaldebrasilia.com.br/feed/" /></outline></body></opml>""",
    "Russia": """<?xml version='1.0' encoding='UTF-8' ?><opml version="1.0"><body><outline text="Russia"><outline text="Lenta.ru" xmlUrl="https://lenta.ru/rss" /><outline text="Vesti.Ru" xmlUrl="https://www.vesti.ru/vesti.rss" /><outline text="Gazeta.Ru" xmlUrl="https://www.gazeta.ru/export/rss/first.xml" /><outline text="Moskovsky Komsomolets" xmlUrl="https://www.mk.ru/rss/index.xml" /><outline text="Rossiyskaya Gazeta" xmlUrl="https://rg.ru/xml/index.xml" /><outline text="NEWSru" xmlUrl="https://rss.newsru.com/top/big/" /><outline text="RT" xmlUrl="https://www.rt.com/rss/" /><outline text="Meduza" xmlUrl="https://meduza.io/rss/all" /><outline text="Russia Insider" xmlUrl="https://russia-insider.com/en/all-content/rss" /><outline text="TASS" xmlUrl="http://tass.com/rss/v2.xml" /><outline text="The Moscow Times" xmlUrl="https://www.themoscowtimes.com/rss/news" /><outline text="Kommersant" xmlUrl="https://www.kommersant.ru/RSS/main.xml" /><outline text="PravdaReport" xmlUrl="https://www.pravdareport.com/export.xml" /></outline></body></opml>"""
}

lang_map = {
    "United States": "en", "United Kingdom": "en", "India": "en", "Canada": "en", "Australia": "en", "South Africa": "en",
    "Germany": "de", "France": "fr", "Japan": "ja", "Brazil": "pt", "Russia": "ru", "Mexico": "es", "Spain": "es", "Italy": "it"
}

sources = []

for country, xml in opml_data.items():
    try:
        root = ET.fromstring(xml)
        for outline in root.findall(".//outline"):
            if "xmlUrl" in outline.attrib:
                sources.append({
                    "name": f"{outline.get('text', 'News')} - {country}",
                    "url": outline.get("xmlUrl"),
                    "type": "RSS",
                    "language": lang_map.get(country, "en"),
                    "region": country,
                    "active": True
                })

    except Exception as e:
        print(f"Error parsing {country}: {e}")

output_file = "news-service/src/main/resources/sources.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(sources, f, indent=2)

print(f"Generated {len(sources)} sources to {output_file}")
